version: '3'
x-common-variables: &common-variables
  MYSQL_DATABASE: photos
  MYSQL_USER: gorman
  MYSQL_PASSWORD: gorman
services:
    mysql:
        # container_name: mysql
        image: mysql
        restart: always
        cap_add:
        - SYS_NICE
        volumes:
        - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
        ports:
          - "3306:3306"
        # - "9906:3306"
        environment:
            <<: *common-variables
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_HOST: mysql
        healthcheck:
         test: ["CMD-SHELL", "mysql -h mysql -u  root -p$$MYSQL_ROOT_PASSWORD" ]
         interval: 30s
         timeout: 20s
         retries: 10
        # networks:
        #     - example-net
    adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql
      environment:
        ADMINER_DEFAULT_SERVER: mysql
      # networks:
      #       - example-net
    mongo:
        container_name: mongo
        image: mongo:4.4.6 #latest at the moment version has an issue with cpu compatibility. Thus - stick with exact working
        hostname: mongo
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017" 
        # networks:
        #     - example-net
# version: '3'
# x-common-variables: &common-variables
#   MYSQL_DATABASE: mangor
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD
# services:
#     mysql_db:
#         image: mysql
#         restart: always
#         cap_add:
#         - SYS_NICE
#         volumes:
#         - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
#         ports:
#         - "9906:3306"
#         environment:
#             <<: *common-variables
#             MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
#             MYSQL_HOST: localhost
#     adminer:
#       image: adminer:latest
#       restart: unless-stopped
#       ports:
#         - 8000:8080
#       depends_on:
#         - mysql_db
#       environment:
#         ADMINER_DEFAULT_SERVER: mysql_db
#     mongo:
#         container_name: mongo
#         image: mongo:4.4.6 #latest at the moment version has an issue with cpu compatibility. Thus - stick with exact working
#         hostname: mongo
#         healthcheck:
#             test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
#             interval: 10s
#             timeout: 10s
#             retries: 5
#             start_period: 40s
#         volumes:
#             - ./data:/data/db
#         ports:
#             - "27017:27017" 